import {
  chmod,
  lstat,
  mkdtemp,
  realpath,
  rename,
  rm,
  unlink,
} from "node:fs/promises";
import {tmpdir} from "node:os";
import {dirname, join, resolve} from "node:path";

const GENERATED_HEADER =
  "# Generated by noctalia-config-sync. Do not edit manually.";
const GENERATED_RELATIVE_PATH =
  "modules/users/leah/_noctalia-config.nix";
const MODULE_RELATIVE_PATH = "modules/users/leah/noctalia.nix";
const HOST = "lilac";
const HELP = `Usage: noctalia-config-sync [REPOSITORY]
Export merged Noctalia GUI settings to Nix, switch lilac, and remove runtime overrides.`;

interface Commands {
  alejandra: string;
  git: string;
  nix: string;
  nixInstantiate: string;
  nixosRebuild: string;
  noctalia: string;
  sudo: string;
}

interface Comparison {
  activeAvatar: unknown;
  activeWallpaper: unknown;
  differingTopLevelKeys: string[];
  equal: boolean;
}

function errorCode(error: unknown): string | undefined {
  if (typeof error !== "object" || error === null || !("code" in error)) {
    return undefined;
  }

  return String(error.code);
}

function formatError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function requireExecutable(name: string): string {
  const executable = Bun.which(name);
  if (executable === null) {
    throw new Error(`required executable not found in PATH: ${name}`);
  }

  return resolve(executable);
}

function resolveCommands(): Commands {
  return {
    alejandra: requireExecutable("alejandra"),
    git: requireExecutable("git"),
    nix: requireExecutable("nix"),
    nixInstantiate: requireExecutable("nix-instantiate"),
    nixosRebuild: requireExecutable("nixos-rebuild"),
    noctalia: requireExecutable("noctalia"),
    sudo: requireExecutable("sudo"),
  };
}

async function runCapture(
  command: string[],
  options: {cwd?: string; env?: NodeJS.ProcessEnv} = {},
): Promise<string> {
  const child = Bun.spawn({
    cmd: command,
    cwd: options.cwd,
    env: options.env ?? process.env,
    stdin: "ignore",
    stdout: "pipe",
    stderr: "inherit",
  });
  const stdout = new Response(child.stdout).text();
  const exitCode = await child.exited;
  const output = await stdout;

  if (exitCode !== 0) {
    throw new Error(
      `${command[0]} exited with status ${exitCode}`,
    );
  }

  return output;
}

async function runInherited(
  command: string[],
  options: {cwd?: string; env?: NodeJS.ProcessEnv; stdin?: boolean} = {},
): Promise<void> {
  const child = Bun.spawn({
    cmd: command,
    cwd: options.cwd,
    env: options.env ?? process.env,
    stdin: options.stdin ? "inherit" : "ignore",
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await child.exited;

  if (exitCode !== 0) {
    throw new Error(
      `${command[0]} exited with status ${exitCode}`,
    );
  }
}

async function requireRegularFile(path: string, description: string) {
  let metadata;
  try {
    metadata = await lstat(path);
  } catch (error) {
    if (errorCode(error) === "ENOENT") {
      throw new Error(`${description} does not exist: ${path}`);
    }
    throw error;
  }

  if (!metadata.isFile()) {
    throw new Error(`${description} is not a regular file: ${path}`);
  }

  return metadata;
}

async function sha256(path: string): Promise<string> {
  const contents = await Bun.file(path).arrayBuffer();
  return new Bun.CryptoHasher("sha256")
    .update(contents)
    .digest("hex");
}

async function requireHash(
  path: string,
  expected: string,
  description: string,
): Promise<void> {
  let actual: string;
  try {
    actual = await sha256(path);
  } catch (error) {
    throw new Error(
      `${description} changed or disappeared: ${path}: ${formatError(error)}`,
    );
  }

  if (actual !== expected) {
    throw new Error(`${description} changed concurrently: ${path}`);
  }
}

function resolveOverridePath(): string {
  const stateHome =
    process.env.NOCTALIA_STATE_HOME ??
    process.env.XDG_STATE_HOME ??
    (process.env.HOME === undefined
      ? undefined
      : join(process.env.HOME, ".local", "state"));

  if (stateHome === undefined || stateHome.length === 0) {
    throw new Error(
      "cannot resolve Noctalia state home: NOCTALIA_STATE_HOME, XDG_STATE_HOME, and HOME are unset",
    );
  }

  return join(stateHome, "noctalia", "settings.toml");
}

async function resolveRepository(
  argument: string | undefined,
  git: string,
): Promise<string> {
  const requested =
    argument === undefined
      ? (
          await runCapture(
            [git, "rev-parse", "--show-toplevel"],
            {cwd: process.cwd()},
          )
        ).trim()
      : resolve(argument);

  if (requested.length === 0) {
    throw new Error("git returned an empty repository root");
  }

  try {
    return await realpath(requested);
  } catch (error) {
    throw new Error(
      `cannot resolve repository root ${requested}: ${formatError(error)}`,
    );
  }
}

const removeOwnedPathsExpression = `settings:
  settings
  // (if settings ? shell then {
    shell = builtins.removeAttrs settings.shell ["avatar_path"];
  } else {})
  // (if settings ? wallpaper then {
    wallpaper = settings.wallpaper // (if settings.wallpaper ? default then {
      default = builtins.removeAttrs settings.wallpaper.default ["path"];
    } else {});
  } else {})`;

const renderExpression = `
let
  nixpkgsPath = builtins.toPath (builtins.getEnv "NOCTALIA_CONFIG_SYNC_NIXPKGS");
  lib = import (nixpkgsPath + "/lib");
  settings = builtins.fromTOML (builtins.readFile (builtins.getEnv "NOCTALIA_CONFIG_SYNC_EXPORT"));
  removeOwnedPaths = ${removeOwnedPathsExpression};
in
  if !builtins.isAttrs settings then
    throw "Noctalia export root is not an attribute set"
  else if settings == {} then
    throw "Noctalia export is empty"
  else
    lib.generators.toPretty {} (removeOwnedPaths settings)
`;

const compareExpression = `
let
  nixpkgsPath = builtins.toPath (builtins.getEnv "NOCTALIA_CONFIG_SYNC_NIXPKGS");
  lib = import (nixpkgsPath + "/lib");
  expected = builtins.fromTOML (builtins.readFile (builtins.getEnv "NOCTALIA_CONFIG_SYNC_EXPECTED"));
  active = builtins.fromTOML (builtins.readFile (builtins.getEnv "NOCTALIA_CONFIG_SYNC_ACTIVE"));
  normalize = ${removeOwnedPathsExpression};
  expectedNormalized = normalize expected;
  activeNormalized = normalize active;
  keys = lib.unique (builtins.attrNames expectedNormalized ++ builtins.attrNames activeNormalized);
  valueAt = set: key: if builtins.hasAttr key set then builtins.getAttr key set else null;
  differingTopLevelKeys = builtins.filter
    (key: valueAt expectedNormalized key != valueAt activeNormalized key)
    keys;
in
  builtins.toJSON {
    activeAvatar = if active ? shell then active.shell.avatar_path or null else null;
    activeWallpaper =
      if active ? wallpaper && active.wallpaper ? default
      then active.wallpaper.default.path or null
      else null;
    inherit differingTopLevelKeys;
    equal = expectedNormalized == activeNormalized;
  }
`;

async function writePrivate(path: string, contents: string): Promise<void> {
  await Bun.write(path, contents);
  await chmod(path, 0o600);
}

async function exportMerged(
  noctalia: string,
  destination: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<void> {
  const output = await runCapture(
    [noctalia, "config", "export", "merged"],
    {env},
  );
  await writePrivate(destination, output);
}

async function pathIsMissing(path: string): Promise<boolean> {
  try {
    await lstat(path);
    return false;
  } catch (error) {
    if (errorCode(error) === "ENOENT") {
      return true;
    }
    throw error;
  }
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.length === 1 && (args[0] === "-h" || args[0] === "--help")) {
    console.log(HELP);
    return;
  }

  if (args.length > 1) {
    throw new Error("expected at most one REPOSITORY argument");
  }
  if (args[0]?.startsWith("-")) {
    throw new Error(`unknown option: ${args[0]}`);
  }

  const nixpkgsPath = process.env.NOCTALIA_CONFIG_SYNC_NIXPKGS;
  if (nixpkgsPath === undefined || nixpkgsPath.length === 0) {
    throw new Error("NOCTALIA_CONFIG_SYNC_NIXPKGS is not set by the package wrapper");
  }

  const commands = resolveCommands();
  const repository = await resolveRepository(args[0], commands.git);
  const modulePath = join(repository, MODULE_RELATIVE_PATH);
  const generatedPath = join(repository, GENERATED_RELATIVE_PATH);
  await requireRegularFile(modulePath, "Noctalia Home Manager module");
  const generatedMetadata = await requireRegularFile(
    generatedPath,
    "generated Noctalia settings",
  );

  const overridePath = resolveOverridePath();
  await requireRegularFile(overridePath, "Noctalia runtime override");

  const generatedOriginalHash = await sha256(generatedPath);
  const overrideOriginalHash = await sha256(overridePath);
  const scratch = await mkdtemp(join(tmpdir(), "noctalia-config-sync-"));
  await chmod(scratch, 0o700);
  const candidateDirectory = await mkdtemp(
    join(dirname(generatedPath), ".noctalia-config-sync-"),
  );
  await chmod(candidateDirectory, 0o700);

  const exportedPath = join(scratch, "exported.toml");
  const activePath = join(scratch, "active.toml");
  const candidatePath = join(candidateDirectory, "_noctalia-config.nix");
  let installedHash: string | undefined;

  try {
    await exportMerged(commands.noctalia, exportedPath);
    await requireHash(
      overridePath,
      overrideOriginalHash,
      "Noctalia runtime override",
    );
    await runInherited([
      commands.noctalia,
      "config",
      "validate",
      exportedPath,
    ]);

    const rendered = await runCapture(
      [commands.nix, "eval", "--impure", "--raw", "--expr", renderExpression],
      {
        env: {
          ...process.env,
          NOCTALIA_CONFIG_SYNC_EXPORT: exportedPath,
        },
      },
    );
    const candidate = `${GENERATED_HEADER}\n${rendered.trimEnd()}\n`;
    await Bun.write(candidatePath, candidate);
    await chmod(candidatePath, generatedMetadata.mode & 0o7777);

    await runInherited([commands.alejandra, "-q", candidatePath]);
    await runCapture([
      commands.nixInstantiate,
      "--parse",
      candidatePath,
    ]);
    const isAttributeSet = (
      await runCapture(
        [
          commands.nix,
          "eval",
          "--impure",
          "--expr",
          'builtins.isAttrs (import (builtins.getEnv "NOCTALIA_CONFIG_SYNC_CANDIDATE"))',
        ],
        {
          env: {
            ...process.env,
            NOCTALIA_CONFIG_SYNC_CANDIDATE: candidatePath,
          },
        },
      )
    ).trim();
    if (isAttributeSet !== "true") {
      throw new Error(
        `generated candidate did not evaluate to an attribute set: ${isAttributeSet}`,
      );
    }

    await requireHash(
      generatedPath,
      generatedOriginalHash,
      "generated Noctalia settings",
    );
    await requireHash(
      overridePath,
      overrideOriginalHash,
      "Noctalia runtime override",
    );

    installedHash = await sha256(candidatePath);
    await rename(candidatePath, generatedPath);

    await runInherited(
      [
        commands.sudo,
        commands.nixosRebuild,
        "switch",
        "--flake",
        `${repository}#${HOST}`,
      ],
      {cwd: repository, stdin: true},
    );

    await requireHash(
      generatedPath,
      installedHash,
      "installed generated Noctalia settings",
    );
    await requireHash(
      overridePath,
      overrideOriginalHash,
      "Noctalia runtime override",
    );

    const emptyStateHome = await mkdtemp(join(scratch, "active-state-"));
    await chmod(emptyStateHome, 0o700);
    await exportMerged(commands.noctalia, activePath, {
      ...process.env,
      NOCTALIA_STATE_HOME: emptyStateHome,
    });

    const comparisonOutput = await runCapture(
      [commands.nix, "eval", "--impure", "--raw", "--expr", compareExpression],
      {
        env: {
          ...process.env,
          NOCTALIA_CONFIG_SYNC_ACTIVE: activePath,
          NOCTALIA_CONFIG_SYNC_EXPECTED: exportedPath,
        },
      },
    );
    let comparison: Comparison;
    try {
      comparison = JSON.parse(comparisonOutput) as Comparison;
    } catch (error) {
      throw new Error(
        `could not parse post-switch comparison: ${formatError(error)}`,
      );
    }

    if (
      typeof comparison.activeAvatar !== "string" ||
      !/^\/nix\/store\/.*-pfp\.jpg$/.test(comparison.activeAvatar)
    ) {
      throw new Error(
        `active shell.avatar_path is not the Nix-owned profile picture: ${JSON.stringify(comparison.activeAvatar)}`,
      );
    }
    if (
      typeof comparison.activeWallpaper !== "string" ||
      !/^\/nix\/store\/.*-nas-flag-wallpaper\.png$/.test(
        comparison.activeWallpaper,
      )
    ) {
      throw new Error(
        `active wallpaper.default.path is not the Nix-owned wallpaper: ${JSON.stringify(comparison.activeWallpaper)}`,
      );
    }
    if (!comparison.equal) {
      throw new Error(
        `post-switch settings differ from the exported GUI settings in top-level keys: ${comparison.differingTopLevelKeys.join(", ")}`,
      );
    }

    await requireHash(
      generatedPath,
      installedHash,
      "installed generated Noctalia settings",
    );
    await requireHash(
      overridePath,
      overrideOriginalHash,
      "Noctalia runtime override",
    );

    try {
      await unlink(overridePath);
    } catch (error) {
      if (errorCode(error) !== "ENOENT") {
        throw error;
      }
    }
    if (!(await pathIsMissing(overridePath))) {
      throw new Error(
        `Noctalia runtime override was recreated before deletion could be verified: ${overridePath}`,
      );
    }

    console.log(`Updated ${generatedPath}`);
    console.log(`Switched ${HOST} from ${repository}`);
    console.log(`Removed ${overridePath}`);
  } finally {
    await rm(candidateDirectory, {recursive: true, force: true});
    await rm(scratch, {recursive: true, force: true});
  }
}

try {
  await main();
} catch (error) {
  console.error(`noctalia-config-sync: ${formatError(error)}`);
  process.exitCode = 1;
}
