#!/usr/bin/env bash
set -Eeuo pipefail

readonly GENERATED_HEADER='# Generated by noctalia-config-sync. Do not edit manually.'
readonly GENERATED_RELATIVE_PATH='modules/users/leah/_noctalia-config.nix'
readonly MODULE_RELATIVE_PATH='modules/users/leah/noctalia.nix'
readonly HOST='lilac'

scratch=''
candidate_directory=''

usage() {
  printf '%s\n' \
    'Usage: noctalia-config-sync [REPOSITORY]' \
    'Export merged Noctalia GUI settings to Nix, switch lilac, and remove runtime overrides.'
}

die() {
  printf 'noctalia-config-sync: %s\n' "$*" >&2
  exit 1
}

cleanup() {
  if [[ -n $candidate_directory ]]; then
    rm -rf -- "$candidate_directory" || true
  fi
  if [[ -n $scratch ]]; then
    rm -rf -- "$scratch" || true
  fi
}
trap cleanup EXIT

hash_file() {
  local output
  if ! output=$(sha256sum -- "$1"); then
    return 1
  fi
  printf '%s\n' "${output%% *}"
}

require_hash() {
  local path=$1
  local expected=$2
  local description=$3
  local actual

  if ! actual=$(hash_file "$path"); then
    die "$description changed or disappeared: $path"
  fi
  if [[ $actual != "$expected" ]]; then
    die "$description changed concurrently: $path"
  fi
}

require_regular_file() {
  local path=$1
  local description=$2

  if [[ ! -f $path || -L $path ]]; then
    die "$description is not a regular file: $path"
  fi
}

case $# in
  0)
    repository=''
    ;;
  1)
    case $1 in
      -h | --help)
        usage
        exit 0
        ;;
      -*)
        die "unknown option: $1"
        ;;
      *)
        repository=$1
        ;;
    esac
    ;;
  *)
    die 'expected at most one REPOSITORY argument'
    ;;
esac

if [[ -z ${NOCTALIA_CONFIG_SYNC_NIXPKGS:-} ]]; then
  die 'NOCTALIA_CONFIG_SYNC_NIXPKGS is not set by the package wrapper'
fi

for required_command in \
  alejandra \
  git \
  nix \
  nix-instantiate \
  nixos-rebuild \
  noctalia \
  sudo; do
  command -v "$required_command" >/dev/null ||
    die "required executable not found in PATH: $required_command"
done

alejandra_command=$(command -v alejandra)
git_command=$(command -v git)
nix_command=$(command -v nix)
nix_instantiate_command=$(command -v nix-instantiate)
nixos_rebuild_command=$(command -v nixos-rebuild)
noctalia_command=$(command -v noctalia)
sudo_command=$(command -v sudo)
readonly \
  alejandra_command \
  git_command \
  nix_command \
  nix_instantiate_command \
  nixos_rebuild_command \
  noctalia_command \
  sudo_command

if [[ -z $repository ]]; then
  repository=$($git_command rev-parse --show-toplevel) ||
    die 'cannot find a Git repository root'
fi
requested_repository=$repository
repository=$(realpath -- "$requested_repository") ||
  die "cannot resolve repository root: $requested_repository"
readonly repository

readonly module_path="$repository/$MODULE_RELATIVE_PATH"
readonly generated_path="$repository/$GENERATED_RELATIVE_PATH"
require_regular_file "$module_path" 'Noctalia Home Manager module'
require_regular_file "$generated_path" 'generated Noctalia settings'

if [[ ${NOCTALIA_STATE_HOME+x} ]]; then
  state_home=$NOCTALIA_STATE_HOME
elif [[ ${XDG_STATE_HOME+x} ]]; then
  state_home=$XDG_STATE_HOME
elif [[ ${HOME+x} ]]; then
  state_home=$HOME/.local/state
else
  die 'cannot resolve Noctalia state home: NOCTALIA_STATE_HOME, XDG_STATE_HOME, and HOME are unset'
fi
if [[ -z $state_home ]]; then
  die 'cannot resolve Noctalia state home from an empty environment variable'
fi
readonly override_path="$state_home/noctalia/settings.toml"
require_regular_file "$override_path" 'Noctalia runtime override'

generated_original_hash=$(hash_file "$generated_path")
override_original_hash=$(hash_file "$override_path")
generated_mode=$(stat -c '%a' -- "$generated_path")
readonly generated_original_hash override_original_hash generated_mode

scratch=$(mktemp -d "${TMPDIR:-/tmp}/noctalia-config-sync.XXXXXX")
chmod 700 "$scratch"
candidate_directory=$(mktemp -d "${generated_path%/*}/.noctalia-config-sync.XXXXXX")
chmod 700 "$candidate_directory"

readonly exported_path="$scratch/exported.toml"
readonly active_path="$scratch/active.toml"
readonly candidate_path="$candidate_directory/_noctalia-config.nix"

render_expression=$(cat <<'NIX'
let
  nixpkgsPath = builtins.toPath (builtins.getEnv "NOCTALIA_CONFIG_SYNC_NIXPKGS");
  lib = import (nixpkgsPath + "/lib");
  settings = builtins.fromTOML (builtins.readFile (builtins.getEnv "NOCTALIA_CONFIG_SYNC_EXPORT"));
  removeOwnedPaths = settings:
    settings
    // (if settings ? shell then {
      shell = builtins.removeAttrs settings.shell ["avatar_path"];
    } else {})
    // (if settings ? wallpaper then {
      wallpaper = settings.wallpaper // (if settings.wallpaper ? default then {
        default = builtins.removeAttrs settings.wallpaper.default ["path"];
      } else {});
    } else {});
in
  if !builtins.isAttrs settings then
    throw "Noctalia export root is not an attribute set"
  else if settings == {} then
    throw "Noctalia export is empty"
  else
    lib.generators.toPretty {} (removeOwnedPaths settings)
NIX
)
readonly render_expression

compare_expression=$(cat <<'NIX'
let
  nixpkgsPath = builtins.toPath (builtins.getEnv "NOCTALIA_CONFIG_SYNC_NIXPKGS");
  lib = import (nixpkgsPath + "/lib");
  expected = builtins.fromTOML (builtins.readFile (builtins.getEnv "NOCTALIA_CONFIG_SYNC_EXPECTED"));
  active = builtins.fromTOML (builtins.readFile (builtins.getEnv "NOCTALIA_CONFIG_SYNC_ACTIVE"));
  normalize = settings:
    settings
    // (if settings ? shell then {
      shell = builtins.removeAttrs settings.shell ["avatar_path"];
    } else {})
    // (if settings ? wallpaper then {
      wallpaper = settings.wallpaper // (if settings.wallpaper ? default then {
        default = builtins.removeAttrs settings.wallpaper.default ["path"];
      } else {});
    } else {});
  expectedNormalized = normalize expected;
  activeNormalized = normalize active;
  activeAvatar = if active ? shell then active.shell.avatar_path or null else null;
  activeWallpaper =
    if active ? wallpaper && active.wallpaper ? default
    then active.wallpaper.default.path or null
    else null;
  keys = lib.unique (builtins.attrNames expectedNormalized ++ builtins.attrNames activeNormalized);
  valueAt = set: key: if builtins.hasAttr key set then builtins.getAttr key set else null;
  differingTopLevelKeys = builtins.filter
    (key: valueAt expectedNormalized key != valueAt activeNormalized key)
    keys;
in
  if !builtins.isString activeAvatar
     || builtins.match "/nix/store/.*-pfp\\.jpg" activeAvatar == null then
    throw "active shell.avatar_path is not the Nix-owned profile picture: ${builtins.toJSON activeAvatar}"
  else if !builtins.isString activeWallpaper
          || builtins.match "/nix/store/.*-nas-flag-wallpaper\\.png" activeWallpaper == null then
    throw "active wallpaper.default.path is not the Nix-owned wallpaper: ${builtins.toJSON activeWallpaper}"
  else if differingTopLevelKeys != [] then
    throw "post-switch settings differ from the exported GUI settings in top-level keys: ${lib.concatStringsSep ", " differingTopLevelKeys}"
  else
    "ok"
NIX
)
readonly compare_expression

"$noctalia_command" config export merged >"$exported_path"
chmod 600 "$exported_path"
require_hash "$override_path" "$override_original_hash" 'Noctalia runtime override'
"$noctalia_command" config validate "$exported_path"

if ! rendered=$(
  NOCTALIA_CONFIG_SYNC_EXPORT="$exported_path" \
    "$nix_command" eval --impure --raw --expr "$render_expression"
); then
  die 'failed to render the merged Noctalia export'
fi
printf '%s\n%s\n' "$GENERATED_HEADER" "$rendered" >"$candidate_path"
chmod "$generated_mode" "$candidate_path"

"$alejandra_command" -q "$candidate_path"
"$nix_instantiate_command" --parse "$candidate_path" >/dev/null
if ! is_attribute_set=$(
  NOCTALIA_CONFIG_SYNC_CANDIDATE="$candidate_path" \
    "$nix_command" eval --impure --expr \
      'builtins.isAttrs (import (builtins.getEnv "NOCTALIA_CONFIG_SYNC_CANDIDATE"))'
); then
  die 'failed to evaluate the generated candidate'
fi
if [[ $is_attribute_set != true ]]; then
  die "generated candidate did not evaluate to an attribute set: $is_attribute_set"
fi

require_hash "$generated_path" "$generated_original_hash" 'generated Noctalia settings'
require_hash "$override_path" "$override_original_hash" 'Noctalia runtime override'

installed_hash=$(hash_file "$candidate_path")
readonly installed_hash
mv -T -- "$candidate_path" "$generated_path"

"$sudo_command" "$nixos_rebuild_command" switch --flake "$repository#$HOST"

require_hash "$generated_path" "$installed_hash" 'installed generated Noctalia settings'
require_hash "$override_path" "$override_original_hash" 'Noctalia runtime override'

empty_state_home=$(mktemp -d "$scratch/active-state.XXXXXX")
chmod 700 "$empty_state_home"
NOCTALIA_STATE_HOME="$empty_state_home" \
  "$noctalia_command" config export merged >"$active_path"
chmod 600 "$active_path"

if ! comparison=$(
  NOCTALIA_CONFIG_SYNC_ACTIVE="$active_path" \
  NOCTALIA_CONFIG_SYNC_EXPECTED="$exported_path" \
    "$nix_command" eval --impure --raw --expr "$compare_expression"
); then
  die 'post-switch Noctalia configuration does not match the exported settings'
fi
if [[ $comparison != ok ]]; then
  die "unexpected post-switch comparison result: $comparison"
fi

require_hash "$generated_path" "$installed_hash" 'installed generated Noctalia settings'
require_hash "$override_path" "$override_original_hash" 'Noctalia runtime override'

rm -f -- "$override_path"
if [[ -e $override_path || -L $override_path ]]; then
  die "Noctalia runtime override was recreated before deletion could be verified: $override_path"
fi

printf 'Updated %s\n' "$generated_path"
printf 'Switched %s from %s\n' "$HOST" "$repository"
printf 'Removed %s\n' "$override_path"
