# Generated by noctalia-config-sync. Do not edit manually.
{
  backdrop = {
    enabled = true;
  };
  bar = {
    order = [
      "widgets"
    ];
    widgets = {
      background_opacity = 0.4999999888241291;
      capsule_group = [
        {
          accordion = false;
          accordion_direction = "end";
          enabled = true;
          fill = "surface_variant";
          id = "g1";
          members = [
            "battery"
            "power_profile"
          ];
          opacity = 0.0;
          padding = 6.0;
        }
      ];
      capsule_radius = 0;
      center = [
        "workspaces"
        "clock"
      ];
      contact_shadow = true;
      dead_zone = {
        actions = {
          back = "annotate";
        };
      };
      end = [
        "tray"
        "notifications"
        "clipboard"
        "network"
        "bluetooth"
        "volume"
        "brightness"
        "group:g1"
        "control-center"
      ];
      radius = 0;
      scale = 1.05;
      start = [
        "launcher"
        "active_window"
        "media"
      ];
      thickness = 36;
      widget_spacing = 8;
    };
  };
  battery = {
    device = {
      "/org/freedesktop/UPower/devices/battery_hidpp_battery_4" = {
        warning_threshold = 10;
      };
      "/org/freedesktop/UPower/devices/keyboard_dev_D3_01_77_24_59_4E" = {
        warning_threshold = 10;
      };
    };
    warning_threshold = 15;
  };
  brightness = {
    enable_ddcutil = true;
  };
  calendar = {
    account = {
      fastmail = {
        color = "primary";
        name = "Fastmail";
        provider = "custom";
        server_url = "https://caldav.fastmail.com/";
        type = "caldav";
        username = "leah@leah.pet";
      };
    };
    enabled = true;
    refresh_minutes = 5;
    reminders = {
      all_day_digest_time = "10:00";
    };
  };
  control_center = {
    calendar = {
      show_week_numbers = true;
    };
    shortcuts = [
      {
        type = "wifi";
      }
      {
        type = "bluetooth";
      }
      {
        type = "caffeine";
      }
      {
        type = "nightlight";
      }
      {
        type = "notification";
      }
      {
        type = "dark_mode";
      }
    ];
    width = 800;
  };
  desktop_widgets = {
    grid = {
      cell_size = 64;
      major_interval = 4;
      visible = true;
    };
    schema_version = 2;
    widget = {
      desktop-widget-0000000000000005 = {
        box_height = 256.0;
        box_width = 512.0;
        cx = 1423.0;
        cy = 568.5;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = -0.0;
        settings = {
          network_speed_compact = false;
          stat = "net_rx";
          stat2 = "net_tx";
        };
        type = "sysmon";
      };
      desktop-widget-0000000000000006 = {
        box_height = 256.0;
        box_width = 512.0;
        cx = 271.0;
        cy = 564.500244140625;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = 0.0;
        settings = {
          stat = "cpu_temp";
          stat2 = "cpu_freq";
        };
        type = "sysmon";
      };
      desktop-widget-0000000000000007 = {
        box_height = 256.0;
        box_width = 576.0;
        cx = 847.0;
        cy = 884.5;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = 0.0;
        settings = {
          stat = "gpu_usage";
          stat2 = "gpu_vram_used";
        };
        type = "sysmon";
      };
      desktop-widget-01 = {
        box_height = 256.0;
        box_width = 512.0;
        cx = 271.0;
        cy = 276.5;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = 0.0;
        settings = {
          shadow = false;
        };
        type = "weather";
      };
      desktop-widget-02 = {
        box_height = 256.0;
        box_width = 512.0;
        cx = 1423.0;
        cy = 276.5;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = 0.0;
        settings = {
          shadow = false;
          stat2 = "ram_pct";
        };
        type = "sysmon";
      };
      desktop-widget-03 = {
        box_height = 256.0;
        box_width = 576.0;
        cx = 847.0;
        cy = 276.5;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = 0.0;
        settings = {
          layout = "horizontal";
          shadow = false;
        };
        type = "media_player";
      };
      desktop-widget-04 = {
        box_height = 256.0;
        box_width = 576.0;
        cx = 847.0;
        cy = 564.5;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = 0.0;
        settings = {
          aspect_ratio = 6.0;
          bands = 32;
          show_when_idle = false;
        };
        type = "audio_visualizer";
      };
    };
    widget_order = [
      "desktop-widget-0000000000000006"
      "desktop-widget-01"
      "desktop-widget-02"
      "desktop-widget-03"
      "desktop-widget-04"
      "desktop-widget-0000000000000005"
      "desktop-widget-0000000000000007"
    ];
  };
  idle = {
    behavior = {
      lock = {
        action = "lock";
        enabled = true;
        timeout = 600;
      };
      lock-and-suspend = {
        action = "lock_and_suspend";
        enabled = true;
        timeout = 900;
      };
      screen-off = {
        action = "screen_off";
        enabled = true;
        timeout = 660;
      };
    };
    behavior_order = [
      "lock"
      "screen-off"
      "lock-and-suspend"
    ];
    pre_action_fade_seconds = 5;
  };
  location = {
    auto_locate = true;
    showWeekNumberInCalendar = true;
    use12hourFormat = true;
    useFahrenheit = true;
  };
  lockscreen = {
    blur_intensity = 0.9999999776482582;
    blurred_desktop = true;
  };
  lockscreen_widgets = {
    enabled = true;
    grid = {
      cell_size = 64;
      major_interval = 4;
      visible = true;
    };
    schema_version = 2;
    widget = {
      "lockscreen-login-box@DP-2" = {
        box_height = 196.0;
        box_width = 720.0;
        cx = 1280.0;
        cy = 1271.0;
        output = "DP-2";
        placement_height = 1440.0;
        placement_width = 2560.0;
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          center_password_text = false;
          input_opacity = 1.0;
          input_radius = 6.0;
          layout = "regular";
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_media = true;
          show_session_buttons = true;
          show_unlock_hint = true;
          show_weather = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@DP-3" = {
        box_height = 196.0;
        box_width = 720.0;
        cx = 1280.0;
        cy = 1321.0;
        output = "DP-3";
        placement_height = 0.0;
        placement_width = 0.0;
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          center_password_text = false;
          input_opacity = 1.0;
          input_radius = 6.0;
          layout = "regular";
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_media = true;
          show_session_buttons = true;
          show_unlock_hint = true;
          show_weather = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@DP-7" = {
        box_height = 196.0;
        box_width = 720.0;
        cx = 512.0;
        cy = 702.4000244140625;
        output = "DP-7";
        placement_height = 768.0;
        placement_width = 1024.0;
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          center_password_text = false;
          input_opacity = 1.0;
          input_radius = 6.0;
          layout = "regular";
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_media = true;
          show_session_buttons = true;
          show_unlock_hint = true;
          show_weather = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@DP-8" = {
        box_height = 196.0;
        box_width = 720.0;
        cx = 1280.0;
        cy = 1317.0;
        output = "DP-8";
        placement_height = 0.0;
        placement_width = 0.0;
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          center_password_text = false;
          input_opacity = 1.0;
          input_radius = 6.0;
          layout = "regular";
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_media = true;
          show_session_buttons = true;
          show_unlock_hint = true;
          show_weather = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@eDP-1" = {
        box_height = 196.0;
        box_width = 720.0;
        cx = 847.0;
        cy = 1006.0004272460938;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          center_password_text = false;
          input_opacity = 1.0;
          input_radius = 6.0;
          layout = "regular";
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_media = true;
          show_session_buttons = true;
          show_unlock_hint = true;
          show_weather = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@winit" = {
        box_height = 196.0;
        box_width = 720.0;
        cx = 942.0;
        cy = 1920.0;
        output = "winit";
        placement_height = 2058.0;
        placement_width = 1884.0;
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          center_password_text = false;
          input_opacity = 1.0;
          input_radius = 6.0;
          layout = "regular";
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_media = true;
          show_session_buttons = true;
          show_unlock_hint = true;
          show_weather = true;
        };
        type = "login_box";
      };
      lockscreen-widget-0000000000000001 = {
        box_height = 192.0;
        box_width = 320.0;
        cx = 1088.0;
        cy = 1091.9998779296875;
        output = "DP-2";
        placement_height = 1440.0;
        placement_width = 2560.0;
        rotation = 0.0;
        settings = {
          shadow = false;
        };
        type = "media_player";
      };
      lockscreen-widget-0000000000000002 = {
        box_height = 0.0;
        box_width = 0.0;
        cx = 1280.0;
        cy = 189.5;
        output = "DP-2";
        placement_height = 1440.0;
        placement_width = 2560.0;
        rotation = 0.0;
        settings = {
          clock_style = "digital";
          color = "primary";
          shadow = false;
        };
        type = "clock";
      };
      lockscreen-widget-0000000000000003 = {
        box_height = 192.0;
        box_width = 320.0;
        cx = 1472.0;
        cy = 1091.9998779296875;
        output = "DP-2";
        placement_height = 1440.0;
        placement_width = 2560.0;
        rotation = 0.0;
        settings = {
          shadow = false;
        };
        type = "weather";
      };
      lockscreen-widget-0000000000000004 = {
        box_height = 0.0;
        box_width = 0.0;
        cx = 847.0;
        cy = 116.5;
        output = "eDP-1";
        placement_height = 1129.0;
        placement_width = 1694.0;
        rotation = 0.0;
        type = "clock";
      };
    };
    widget_order = [
      "lockscreen-login-box@DP-3"
      "lockscreen-login-box@DP-8"
      "lockscreen-login-box@winit"
      "lockscreen-login-box@DP-7"
      "lockscreen-login-box@eDP-1"
      "lockscreen-login-box@DP-2"
      "lockscreen-widget-0000000000000001"
      "lockscreen-widget-0000000000000002"
      "lockscreen-widget-0000000000000003"
      "lockscreen-widget-0000000000000004"
    ];
  };
  nightLight = {
    enabled = true;
    nightTemp = "4525";
  };
  notification = {
    background_opacity = 0.7499999832361937;
    layer = "overlay";
  };
  osd = {
    background_opacity = 0.6999999843537807;
  };
  plugins = {
    enabled = [
      "noctalia/bongocat"
      "noctalia/screen_recorder"
      "noctalia/timer"
    ];
  };
  shell = {
    corner_radius_scale = 0.0;
    external_ip_enabled = true;
    greeter_sync = {
      auto_sync = true;
    };
    niri_overview_type_to_launch_enabled = true;
    panel = {
      clipboard_placement = "attached";
      launcher_placement = "attached";
      launcher_session_search = true;
      transparency_mode = "glass";
    };
    password_style = "random";
    polkit_agent = true;
    screen_time_enabled = true;
    settings_show_advanced = true;
    settings_window_translucent = true;
    telemetry_enabled = true;
    ui_scale = 1.05;
    window_switcher = {
      mru = true;
    };
  };
  theme = {
    builtin = "Catppuccin";
    community_palette = "Oxocarbon";
    mode = "dark";
    source = "builtin";
    templates = {
      builtin_ids = [
        "btop"
        "gtk3"
        "gtk4"
        "ghostty"
        "niri"
        "qt"
        "starship"
      ];
      community_ids = [
        "antigravity"
        "opencode"
        "pi-agent"
        "zen-browser"
        "discord"
        "neovim"
        "obsidian"
        "vscode"
        "prismlauncher"
        "steam"
      ];
    };
    wallpaper_scheme = "m3-content";
  };
  wallpaper = {
    default = {};
    directory = "/home/leah/Pictures/Wallpapers";
    fillColor = "#b89cff";
    overviewEnabled = true;
    transition_on_startup = true;
  };
  weather = {
    refresh_minutes = 5;
    unit = "imperial";
  };
  widget = {
    active_window = {
      capsule = true;
      capsule_opacity = 0.0;
    };
    clock = {
      format = "{:%H:%M:%S}";
      tooltip_format = "%D";
    };
    media = {
      capsule = true;
      hide_when_no_media = true;
    };
    network = {
      show_label = false;
    };
    tray = {
      match_adjacent_spacing = true;
    };
    workspaces = {
      hide_when_empty = true;
    };
  };
}
