# Generated by noctalia-config-sync. Do not edit manually.
{
  backdrop = {
    enabled = true;
  };
  bar = {
    order = [
      "widgets"
    ];
    widgets = {
      capsule_group = [
        {
          fill = "surface_variant";
          id = "g1";
          members = [
            "battery"
            "power_profile"
          ];
          opacity = 1.0;
          padding = 6.0;
        }
      ];
      center = [];
      end = [
        "media"
        "tray"
        "notifications"
        "clipboard"
        "network"
        "bluetooth"
        "volume"
        "brightness"
        "group:g1"
        "clock"
        "control-center"
        "session"
      ];
      scale = 1.05;
      start = [
        "launcher"
        "workspaces"
        "active_window"
      ];
      thickness = 36;
      widget_spacing = 8;
    };
  };
  battery = {
    device = {
      "/org/freedesktop/UPower/devices/battery_hidpp_battery_4" = {
        warning_threshold = 10;
      };
      "/org/freedesktop/UPower/devices/keyboard_dev_D3_01_77_24_59_4E" = {
        warning_threshold = 10;
      };
    };
    warning_threshold = 15;
  };
  calendar = {
    account = {
      fastmail = {
        color = "primary";
        name = "Fastmail";
        provider = "custom";
        server_url = "https://caldav.fastmail.com/dav/calendars/user/catgirl@catgirlin.space/4CBFA88C-345D-11EF-8764-EE226724C8BD";
        type = "caldav";
        username = "catgirl@catgirlin.space";
      };
    };
    enabled = true;
    refresh_minutes = 5;
  };
  control_center = {
    shortcuts = [
      {
        type = "wifi";
      }
      {
        type = "bluetooth";
      }
      {
        type = "caffeine";
      }
      {
        type = "nightlight";
      }
      {
        type = "notification";
      }
      {
        type = "dark_mode";
      }
    ];
  };
  desktop_widgets = {
    grid = {
      cell_size = 64;
      major_interval = 4;
      visible = true;
    };
    schema_version = 2;
    widget = {
      desktop-widget-01 = {
        box_height = 256.0;
        box_width = 576.0;
        cx = 303.0;
        cy = 276.5;
        output = "eDP-1";
        rotation = 0.0;
        settings = {
          shadow = false;
        };
        type = "weather";
      };
      desktop-widget-02 = {
        box_height = 256.0;
        box_width = 448.0;
        cx = 1455.0;
        cy = 276.5;
        output = "eDP-1";
        rotation = 0.0;
        settings = {
          shadow = false;
          stat2 = "ram_pct";
        };
        type = "sysmon";
      };
      desktop-widget-03 = {
        box_height = 256.0;
        box_width = 576.0;
        cx = 911.0;
        cy = 276.5;
        output = "eDP-1";
        rotation = 0.0;
        settings = {
          layout = "horizontal";
          shadow = false;
        };
        type = "media_player";
      };
      desktop-widget-04 = {
        box_height = 128.0;
        box_width = 576.0;
        cx = 911.0;
        cy = 500.5;
        output = "eDP-1";
        rotation = 0.0;
        settings = {
          aspect_ratio = 6.0;
          bands = 32;
          show_when_idle = true;
        };
        type = "audio_visualizer";
      };
    };
    widget_order = [
      "desktop-widget-01"
      "desktop-widget-02"
      "desktop-widget-03"
      "desktop-widget-04"
    ];
  };
  idle = {
    behavior = {
      lock = {
        action = "lock";
        enabled = true;
        timeout = 600;
      };
      lock-and-suspend = {
        action = "lock_and_suspend";
        enabled = true;
        timeout = 900;
      };
      screen-off = {
        action = "screen_off";
        enabled = true;
        timeout = 660;
      };
    };
    behavior_order = [
      "lock"
      "screen-off"
      "lock-and-suspend"
    ];
    pre_action_fade_seconds = 5;
  };
  location = {
    auto_locate = true;
    showWeekNumberInCalendar = true;
    use12hourFormat = true;
    useFahrenheit = true;
  };
  lockscreen_widgets = {
    enabled = true;
    grid = {
      cell_size = 64;
      major_interval = 4;
      visible = true;
    };
    schema_version = 2;
    widget = {
      "lockscreen-login-box@DP-2" = {
        box_height = 70.0;
        box_width = 400.0;
        cx = 1280.0;
        cy = 1271.0;
        output = "DP-2";
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          input_opacity = 1.0;
          input_radius = 6.0;
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_password_hint = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@DP-3" = {
        box_height = 70.0;
        box_width = 400.0;
        cx = 1280.0;
        cy = 1321.0;
        output = "DP-3";
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          input_opacity = 1.0;
          input_radius = 6.0;
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_password_hint = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@DP-7" = {
        box_height = 70.0;
        box_width = 400.0;
        cx = 1280.0;
        cy = 1317.0;
        output = "DP-7";
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          input_opacity = 1.0;
          input_radius = 6.0;
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_password_hint = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@DP-8" = {
        box_height = 70.0;
        box_width = 400.0;
        cx = 1280.0;
        cy = 1317.0;
        output = "DP-8";
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          input_opacity = 1.0;
          input_radius = 6.0;
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_password_hint = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@eDP-1" = {
        box_height = 70.0;
        box_width = 400.0;
        cx = 847.0;
        cy = 1006.0;
        output = "eDP-1";
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          input_opacity = 1.0;
          input_radius = 6.0;
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_password_hint = true;
        };
        type = "login_box";
      };
      "lockscreen-login-box@winit" = {
        box_height = 70.0;
        box_width = 400.0;
        cx = 942.0;
        cy = 1920.0;
        output = "winit";
        rotation = 0.0;
        settings = {
          background_color = "surface_variant";
          background_opacity = 0.88;
          background_radius = 12.0;
          input_opacity = 1.0;
          input_radius = 6.0;
          show_caps_lock = true;
          show_keyboard_layout = true;
          show_login_button = true;
          show_password_hint = true;
        };
        type = "login_box";
      };
      lockscreen-widget-0000000000000001 = {
        box_height = 192.0;
        box_width = 320.0;
        cx = 1088.0;
        cy = 1091.9998779296875;
        output = "DP-2";
        rotation = 0.0;
        settings = {
          shadow = false;
        };
        type = "media_player";
      };
      lockscreen-widget-0000000000000002 = {
        box_height = 0.0;
        box_width = 0.0;
        cx = 1280.0;
        cy = 189.5;
        output = "DP-2";
        rotation = 0.0;
        settings = {
          clock_style = "digital";
          color = "primary";
          shadow = false;
        };
        type = "clock";
      };
      lockscreen-widget-0000000000000003 = {
        box_height = 192.0;
        box_width = 320.0;
        cx = 1472.0;
        cy = 1091.9998779296875;
        output = "DP-2";
        rotation = 0.0;
        settings = {
          shadow = false;
        };
        type = "weather";
      };
    };
    widget_order = [
      "lockscreen-login-box@DP-3"
      "lockscreen-login-box@DP-8"
      "lockscreen-login-box@winit"
      "lockscreen-login-box@DP-7"
      "lockscreen-login-box@eDP-1"
      "lockscreen-login-box@DP-2"
      "lockscreen-widget-0000000000000001"
      "lockscreen-widget-0000000000000002"
      "lockscreen-widget-0000000000000003"
    ];
  };
  nightLight = {
    enabled = true;
    nightTemp = "4525";
  };
  plugins = {
    enabled = [
      "noctalia/bongocat"
      "noctalia/screen_recorder"
      "noctalia/timer"
    ];
  };
  shell = {
    greeter_sync = {
      auto_sync = true;
    };
    niri_overview_type_to_launch_enabled = true;
    panel = {
      clipboard_placement = "attached";
      launcher_placement = "attached";
      launcher_session_search = true;
      transparency_mode = "glass";
    };
    password_style = "random";
    polkit_agent = true;
    screen_time_enabled = true;
    settings_show_advanced = true;
    telemetry_enabled = true;
    ui_scale = 1.05;
  };
  theme = {
    builtin = "Tokyo-Night";
    mode = "auto";
    source = "builtin";
    templates = {
      builtin_ids = [
        "btop"
        "gtk3"
        "gtk4"
        "ghostty"
        "niri"
        "qt"
      ];
      community_ids = [
        "pi-agent"
        "zen-browser"
        "neovim"
        "obsidian"
        "discord"
        "steam"
      ];
    };
    wallpaper_scheme = "m3-content";
  };
  wallpaper = {
    default = {};
    directory = "/home/leah/Pictures/Wallpapers";
    fillColor = "#b89cff";
    overviewEnabled = true;
  };
  weather = {
    refresh_minutes = 5;
    unit = "imperial";
  };
  widget = {
    active_window = {
      capsule = true;
    };
    clock = {
      format = "{:%H:%M:%S}";
      tooltip_format = "%D";
    };
    media = {
      capsule = true;
      hide_when_no_media = true;
    };
    network = {
      show_label = false;
    };
    tray = {
      match_adjacent_spacing = true;
    };
    workspaces = {
      hide_when_empty = true;
    };
  };
}
